# Generated by Django 6.0.2 on 2026-02-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarketzanzibar", "0002_alter_category_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="sale",
            name="assigned_driver",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_sales", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="sale",
            name="delivery_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(choices=[("pending_payment", "Pending Payment"), ("payment_confirmed", "Payment Confirmed"), ("processing", "Processing"), ("out_for_delivery", "Out For Delivery"), ("delivered", "Delivered"), ("cash_completed", "Cash Completed")], default="pending_payment", max_length=30),
        ),
        migrations.AddField(
            model_name="sale",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("control_number", models.CharField(blank=True, max_length=20, unique=True)),
                ("payment_method", models.CharField(default="mobile_money", max_length=50)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("proof_image", models.ImageField(blank=True, null=True, upload_to="payments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="confirmed_payments", to=settings.AUTH_USER_MODEL)),
                ("sale", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payment", to="supermarketzanzibar.sale")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
