# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supermarketzanzibar", "0003_payment_sale_updates_and_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sale",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
